language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - uname -a
  - lsb_release --all

install:
  - sudo apt-get --assume-yes install pandoc

script:
  - make clean
  - make
  - make test
  - sudo make install
  - which youtube-dl
  - youtube-dl --version

notifications:
  email:
    - filippo.valsorda@gmail.com
    - phihag@phihag.de
    - jaime.marquinez.ferrandiz+travis@gmail.com
    - yasoob.khld@gmail.com
#  irc:
#    channels:
#      - "irc.freenode.org#youtube-dl"
#    skip_join: true
